# -*- coding: utf-8 -*-

# Generated by Django 1.11.5 on 2017-09-19 02:40
from __future__ import unicode_literals

import CardSystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=18)),
                ('title', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=16)),
                ('phone', models.IntegerField()),
                ('qq', models.IntegerField()),
                ('wechat', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=50)),
                ('background', models.FileField(upload_to=CardSystem.models.background_path)),
                ('image0', models.FileField(upload_to=CardSystem.models.image_path)),
                ('image1', models.FileField(upload_to=CardSystem.models.image_path)),
                ('image2', models.FileField(upload_to=CardSystem.models.image_path)),
                ('image3', models.FileField(upload_to=CardSystem.models.image_path)),
                ('image4', models.FileField(upload_to=CardSystem.models.image_path)),
                ('image5', models.FileField(upload_to=CardSystem.models.image_path)),
                ('image6', models.FileField(upload_to=CardSystem.models.image_path)),
                ('image7', models.FileField(upload_to=CardSystem.models.image_path)),
                ('image8', models.FileField(upload_to=CardSystem.models.image_path)),
                ('image9', models.FileField(upload_to=CardSystem.models.image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('phone', models.IntegerField()),
                ('content', models.TextField(max_length=200)),
                ('target_user', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=18)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
