# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
